#!/usr/bin/env bash
# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
set -x
. /etc/confluent/docker/bash-config

unset `env | grep -E ^${CHARM_NAME}_SERVICE_ | cut -d "=" -f 1`
unset `env | grep -E ^${CHARM_NAME}_PORT | cut -d "=" -f 1`

/etc/confluent/docker/run