# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: '53 0 * * *'  # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:
    outputs:
      artifact-prefix:
        description: build_charm.yaml `artifact-prefix` output
        value: ${{ jobs.build.outputs.artifact-prefix }}

env:
  JUJU_CHANNEL: "3.6/stable"
  MICROK8S_CHANNEL: "1.28-strict/stable"
  JUJU_BOOTSTRAP_OPTIONS: "--agent-version 3.6.8"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tox & poetry
        run: |
          pipx install tox
          pipx install poetry
      - name: Run linters
        run: tox run -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tox & poetry
        run: |
          sudo apt-get update
          # We need JDK for TLSManager unit tests.
          sudo apt-get install -y default-jdk-headless
          pipx install tox
          pipx install poetry
      - name: Run tests
        run: tox run -e unit

  build:
    strategy:
      matrix:
        path:
          - .
          - tests/integration/app-charm
    name: Build charm | ${{ matrix.path }}
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v29.0.0
    with:
      path-to-charm-directory: ${{ matrix.path }}
      cache: false # TODO: fix after added to the charmcraftcache

  integration-test-github:
    strategy:
      fail-fast: false
      matrix:
        tox-environments:
          - integration-charm
          - integration-provider
          - integration-password-rotation
          - integration-tls
          - integration-tls-complex
          - integration-kraft
          - integration-kraft-tls
          - integration-ha
          # - integration-upgrade
        kraft-mode:
          - single
    name: ${{ matrix.tox-environments }} | ${{ matrix.kraft-mode }}
    needs:
      - lint
      - unit-test
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: ${{ env.MICROK8S_CHANNEL }}
          juju-channel: ${{ env.JUJU_CHANNEL }}
          bootstrap-options: ${{ env.JUJU_BOOTSTRAP_OPTIONS }}
      - name: Download packed charm(s)
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.build.outputs.artifact-prefix }}-*
          merge-multiple: true
      - name: Select tests
        id: select-tests
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]
          then
            echo Running unstable and stable tests
            echo "mark_expression=" >> $GITHUB_OUTPUT
          else
            echo Skipping unstable tests
            echo "mark_expression=not unstable" >> $GITHUB_OUTPUT
          fi
      - name: Run integration tests
        run: tox run -e ${{ matrix.tox-environments }} -- -m '${{ steps.select-tests.outputs.mark_expression }}' --kraft-mode ${{ matrix.kraft-mode }}
        env:
          CI_PACKED_CHARMS: ${{ needs.build.outputs.charms }}


  integration-test-self-hosted:
    strategy:
      fail-fast: false
      matrix:
        tox-environments:
          - integration-charm
          - integration-provider
          - integration-password-rotation
          - integration-tls
          - integration-tls-complex
          - integration-balancer-single
          - integration-balancer-multi
          - integration-kraft
          - integration-kraft-tls
          - integration-ha
          - integration-ha-controller
          # - integration-upgrade
        kraft-mode:
          - multi
    name: ${{ matrix.tox-environments }} | ${{ matrix.kraft-mode }}
    needs:
      - lint
      - unit-test
      - build
    runs-on: [self-hosted, linux, AMD64, X64, xlarge, noble]
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup operator environment
        run: |
          sudo snap install concierge --classic
          # calico has issues with strict confinements, so remove -strict
          sudo snap install microk8s --channel ${MICROK8S_CHANNEL//"-strict"/} --classic
          sudo snap install juju --channel $JUJU_CHANNEL

          sudo usermod -a -G microk8s $USER
          mkdir -p ~/.kube
          chmod 0700 ~/.kube

          sudo tee /var/snap/microk8s/current/args/certs.d/docker.io/hosts.toml << EOF
          server = "$DOCKERHUB_MIRROR"
          [host."${DOCKERHUB_MIRROR#'https://'}"]
          capabilities = ["pull", "resolve"]
          EOF

          sudo microk8s stop
          sudo microk8s start

          # make juju work with microk8s --classic
          sudo mkdir -p /var/snap/juju/current/microk8s/credentials
          sudo microk8s config | sudo tee /var/snap/juju/current/microk8s/credentials/client.config
          sudo chown -R $USER:$USER /var/snap/juju/current/microk8s/credentials

          sudo concierge prepare \
            -p microk8s \
            --microk8s-channel ${MICROK8S_CHANNEL//"-strict"/} \
            --juju-channel $JUJU_CHANNEL \
            --extra-debs pipx
          
          pipx ensurepath
          pipx install tox poetry
      - name: Download packed charm(s)
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.build.outputs.artifact-prefix }}-*
          merge-multiple: true
      - name: Select tests
        id: select-tests
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]
          then
            echo Running unstable and stable tests
            echo "mark_expression=" >> $GITHUB_OUTPUT
          else
            echo Skipping unstable tests
            echo "mark_expression=not unstable" >> $GITHUB_OUTPUT
          fi
      - name: Run integration tests
        run: tox run -e ${{ matrix.tox-environments }} -- -m '${{ steps.select-tests.outputs.mark_expression }}' --kraft-mode ${{ matrix.kraft-mode }}
        env:
          CI_PACKED_CHARMS: ${{ needs.build.outputs.charms }}
